name: Update README with Script Content

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update README.md
      uses: ./.github/actions/update-readme

    - name: Check for changes in README.md
      run: |
        if git diff --quiet README.md; then
          echo 'No changes detected in README.md.'
          echo "changes=false" >> $GITHUB_ENV
        else
          echo 'Changes detected in README.md.'
          echo "changes=true" >> $GITHUB_ENV
        fi

    - name: Commit and push changes
      if: env.changes == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
        git add README.md
        git commit -m 'Auto README.md update with actual script content'
        git push:wq

